/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreightLoadsRouteImport } from './routes/freight-loads'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as FreightLoadIdRouteImport } from './routes/freight-load.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightLoadsRoute = FreightLoadsRouteImport.update({
  id: '/freight-loads',
  path: '/freight-loads',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightLoadIdRoute = FreightLoadIdRouteImport.update({
  id: '/freight-load/$id',
  path: '/freight-load/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/freight-loads': typeof FreightLoadsRoute
  '/stats': typeof StatsRoute
  '/freight-load/$id': typeof FreightLoadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/freight-loads': typeof FreightLoadsRoute
  '/stats': typeof StatsRoute
  '/freight-load/$id': typeof FreightLoadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/freight-loads': typeof FreightLoadsRoute
  '/stats': typeof StatsRoute
  '/freight-load/$id': typeof FreightLoadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/freight-loads' | '/stats' | '/freight-load/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/freight-loads' | '/stats' | '/freight-load/$id'
  id: '__root__' | '/' | '/freight-loads' | '/stats' | '/freight-load/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreightLoadsRoute: typeof FreightLoadsRoute
  StatsRoute: typeof StatsRoute
  FreightLoadIdRoute: typeof FreightLoadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight-loads': {
      id: '/freight-loads'
      path: '/freight-loads'
      fullPath: '/freight-loads'
      preLoaderRoute: typeof FreightLoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight-load/$id': {
      id: '/freight-load/$id'
      path: '/freight-load/$id'
      fullPath: '/freight-load/$id'
      preLoaderRoute: typeof FreightLoadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreightLoadsRoute: FreightLoadsRoute,
  StatsRoute: StatsRoute,
  FreightLoadIdRoute: FreightLoadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
