name: Validate Code

on:
  workflow_call:

jobs:
  typecheck:
    name: Run Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js Ecosystem
        uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: npm ci

      - name: Run Type Checks
        run: npm run typecheck

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js Ecosystem
        uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js Ecosystem
        uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test-run
